trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ganapathy

jobs:
- job: Build
  displayName: 'Build Job'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: my-template.yml  # Reference the template file
    parameters:
      parameter1: 'Hello World'  # Pass parameter with value to the template
