# azure-pipelines.yml

trigger:
- main

jobs:
- job: Build
  displayName: 'Build Job'
pool:
  vmImage: 'ubuntu-latest'
variables:
- group: ganapathy
steps:
- script: echo "The value of test variable is $(test)" $(test)
  displayName: 'Print Test Variable Value'
- template: my-template.yml  # Reference the template file
  parameters:
    parameter1: 'Hello World 123'  # Pass parameter with value to the template
