trigger:
  branches:
    include:
      - main

parameters:
  - name: environment
    type: string
    default: 'production'

jobs:
- job: PassParameter
  displayName: Pass Parameter Job
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: echo "The environment is $(environment)"
    displayName: 'Display Environment'
